name: Deploy site

on:
  workflow_dispatch:
  workflow_run:
    workflows: [Release]
    types: [completed]
    branches: [main, alpha, beta]

permissions:
  pages: write
  id-token: write

jobs:
  build-site:
    uses: ./.github/workflows/_build-site.yml

  deploy-site:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-site
    steps:
      - name: Download site
        uses: actions/cache/restore@v3
        with:
          path: ./website/build
          key: website-${{ needs.build-site.outputs.version }}-${{ github.run_id }}

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./website/build

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2